[server]
# Server configuration
host = "0.0.0.0"
port = 8000

[docker]
# Default Docker image name
default_image = "python-sandbox:latest"
# Dockerfile path
dockerfile_path = "Dockerfile"
# Whether to check for Dockerfile changes and rebuild if needed
check_dockerfile_changes = true
# File to store last build information
build_info_file = ".docker_build_info"

[logging]
# Logging configuration
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_file = "mcp_sandbox.log"

# PyPI index url for pip install
pypi_index_url = "https://pypi.tuna.tsinghua.edu.cn/simple"